# Generated by Django 5.0.3 on 2024-03-21 11:11

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('title', models.CharField(default='درباره ما', max_length=150, verbose_name='موضوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('master_image', models.ImageField(blank=True, null=True, upload_to=contents.models.upload_about_us_image_path, verbose_name='تصویر اصلی')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'انواع درباره ما',
            },
        ),
    ]
