# Generated by Django 5.0.3 on 2024-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.AddField(
            model_name='about',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بلند'),
        ),
        migrations.AddField(
            model_name='about',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کوتا'),
        ),
    ]
