# Generated by Django 5.0.3 on 2024-03-21 13:53

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_remove_about_description_about_long_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('super', models.BooleanField(default=True, verbose_name='ویژه / غیر ویژه')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('position', models.CharField(max_length=150, verbose_name='جایگاه')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=contents.models.upload_avatar_image_path, verbose_name='تصویر پروفایل')),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'افراد',
            },
        ),
    ]
