# Generated by Django 5.0.3 on 2024-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_team_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='team',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=' لینک تلگرام'),
        ),
    ]
