# Generated by Django 5.0.3 on 2024-03-21 14:55

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_team_instagram_team_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('name', models.CharField(max_length=150, verbose_name='نام پروزه')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع پروژه')),
                ('about_project', models.CharField(blank=True, max_length=150, null=True, verbose_name=' درباره پروژه')),
                ('p_picture', models.ImageField(blank=True, null=True, upload_to=contents.models.upload_project_image_path, verbose_name='تصویر پروفایل')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
