# Generated by Django 5.0.3 on 2024-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='about_project',
            field=models.TextField(blank=True, null=True, verbose_name='درباره پروژه'),
        ),
    ]
