# Generated by Django 5.0.3 on 2024-03-21 22:16

import contents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_projects_area_projects_employer_projects_engineer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('pimage', models.ImageField(blank=True, null=True, upload_to=contents.models.upload_propic_image_path, verbose_name='تصویر ')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.projects', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'تصویر پروژه',
                'verbose_name_plural': 'تصاویر پروژه',
            },
        ),
    ]
