# Generated by Django 5.0.3 on 2024-03-21 23:48

import contents.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_projectpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpicture',
            name='pimage',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1024, 614], upload_to=contents.models.upload_propic_image_path, verbose_name='تصویر '),
        ),
    ]
