# Generated by Django 5.0.3 on 2024-03-22 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_remove_projectpicture_pimage_projectpicture_pimage1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpicture',
            old_name='pimage1',
            new_name='pimage',
        ),
    ]
