# Generated by Django 5.0.3 on 2024-03-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_rename_pimage1_projectpicture_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='موضوع شرکت'),
        ),
    ]
