# Generated by Django 5.0.3 on 2024-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='discription1',
            field=models.CharField(default='', max_length=100, verbose_name='1توضیحات'),
        ),
        migrations.AddField(
            model_name='services',
            name='discription2',
            field=models.CharField(default='', max_length=100, verbose_name='2توضیحات'),
        ),
        migrations.AddField(
            model_name='services',
            name='discription3',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='3توضیحات'),
        ),
        migrations.AddField(
            model_name='services',
            name='discription4',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='4توضیحات'),
        ),
        migrations.AddField(
            model_name='services',
            name='name1',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='1عنوان'),
        ),
        migrations.AddField(
            model_name='services',
            name='name2',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='2عنوان'),
        ),
        migrations.AddField(
            model_name='services',
            name='name3',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='عنوان3'),
        ),
        migrations.AddField(
            model_name='services',
            name='name4',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='4عنوان'),
        ),
        migrations.AlterField(
            model_name='services',
            name='discription',
            field=models.CharField(default='', max_length=100, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='عنوان'),
        ),
    ]
