# Generated by Django 5.0.3 on 2024-03-22 14:07

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_remove_services_discription_remove_services_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان مقاله')),
                ('time', models.CharField(blank=True, max_length=150, null=True, verbose_name='زمان پروژه')),
                ('category', models.CharField(max_length=150, verbose_name='دسته بندی')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن مقاله')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=contents.models.upload_articles_image_path, verbose_name='تصویر کوچک مقاله')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=contents.models.upload_articles_image_path, verbose_name='تصویر بزرگ مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.AlterField(
            model_name='services',
            name='discription1',
            field=models.CharField(default='', max_length=150, verbose_name='1توضیحات'),
        ),
        migrations.AlterField(
            model_name='services',
            name='discription2',
            field=models.CharField(default='', max_length=150, verbose_name='2توضیحات'),
        ),
        migrations.AlterField(
            model_name='services',
            name='discription3',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='3توضیحات'),
        ),
        migrations.AlterField(
            model_name='services',
            name='discription4',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='4توضیحات'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='1عنوان'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='2عنوان'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='عنوان3'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name4',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='4عنوان'),
        ),
    ]
