# Generated by Django 5.0.3 on 2024-03-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_articles_alter_services_discription1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='shorttext',
            field=models.CharField(default='', max_length=250, verbose_name='دسته بندی'),
        ),
    ]
