# Generated by Django 5.0.3 on 2024-03-22 15:09

import contents.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_articles_shorttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='shorttext',
            field=models.CharField(default='', max_length=250, verbose_name='متن کوتاه'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='زمان مقاله'),
        ),
        migrations.CreateModel(
            name='ArticlesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('name', models.CharField(max_length=150, verbose_name='نام فایل')),
                ('afile', models.FileField(blank=True, null=True, upload_to=contents.models.upload_file_path, verbose_name='فایل ')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.articles', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'فایل مقاله',
                'verbose_name_plural': 'فایل های مقاله ها',
            },
        ),
    ]
