# Generated by Django 5.0.3 on 2024-03-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0019_alter_articles_shorttext_alter_articles_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='تلفن'),
        ),
    ]
