# Generated by Django 5.0.3 on 2024-03-22 22:35

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0020_about_address_about_email_about_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('name', models.CharField(max_length=150, verbose_name='نام مشتری')),
                ('cimage', models.ImageField(blank=True, null=True, upload_to=contents.models.upload_propic_image_path, verbose_name='تصویر ')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
            },
        ),
    ]
